swagger: "2.0"
info:
  title: Payments
  description: Payments app enables bill payments
  version: 1.0.0

basePath: /payments/v1/
consumes:
  - application/json
produces:
  - application/json


paths:
  /airtime:
    get:
      tags: [Airtime Recharge]
      operationId: payments.wallets_api.airtime_recharge
      summary: Top up airtime
      description: Performs recharge for the supplied phone number and provider code (example "airtel") from the user's wallet
      produces:
        - application/json
      parameters:
        - in: query
          name: phone_number
          type: string
          required: true
        - in: query
          name: amount
          type: integer
          required: true
        - in: query
          name: provider_code
          type: string
          required: true
  #        schema:
  #          $ref: '#/definitions/AirtimeRecharge'
      responses:
        200:
          description: Success
        401:
          description: Authentication failed
        440:
          description: Session expired, login again

#definitions:
#  AirtimeRecharge:
#    type: object
#    properties:
#      phone_number:
#        type: string
#      amount:
#        type: integer
#      provider_code:
#        type: string

